DROP TABLE IF EXISTS `user`;
CREATE TABLE `wenda2`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL DEFAULT '',
  `password` VARCHAR(256) NOT NULL DEFAULT '',
  `salt` VARCHAR(45) NOT NULL DEFAULT '',
  `head_url` VARCHAR(256) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),

  UNIQUE INDEX `name_UNIQUE` (`name` ASC));
